#existing brew packages from old machine. Only here for reference

tap "caskroom/cask"
tap "heroku/brew"
tap "homebrew/bundle"
tap "homebrew/core"
cask "java"
brew "sqlite"
brew "awscli"
brew "clojure"
brew "git"
brew "mongodb"
brew "postgresql"
brew "rbenv"
brew "yarn", args: ["without-node"]
brew "zsh"
brew "zsh-completions"
brew "heroku/brew/heroku"
